name: Tests Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment where you want to deploy.'
        required: true
        default: 'staging'
        type: choice
        options:
        - prod
        - staging

jobs:

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./docker_run.sh
        env:
          ENVIRONMENT: ${{ inputs.environment }}